<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
$optionsHelper = $this->helper('Zemez\ThemeOptions\Helper\Data');
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<span data-action="toggle-nav" class="action nav-toggle"><span><?= /* @escapeNotVerified */ __('Toggle Nav') ?></span></span>
<a class="logo" href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>" aria-label="store logo">
    <?php if($optionsHelper->getLogoType() == 'image'): ?>
        <img src="<?= /* @escapeNotVerified */ $block->getLogoSrc() ?>"
             title="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
             alt="<?= $block->escapeHtmlAttr($block->getLogoAlt()) ?>"
            <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
            <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
        />
        <?php if($optionsHelper->isImageSlogan()): ?>
            <span class="slogan <?= $optionsHelper->getImageSloganPosition(); ?>">
                <?= $optionsHelper->getImageSloganText(); ?>
            </span>
        <?php endif; ?>
    <?php else:?>
        <span class="logo-text"><?= $optionsHelper->getLogoText(); ?></span>
        <?php if($optionsHelper->isSlogan()): ?>
            <strong class="slogan <?= $optionsHelper->getSloganPosition(); ?>">
                <?= $optionsHelper->getSloganText(); ?>
            </strong>
        <?php endif; ?>
    <?php endif?>
</a>
