<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Comment $block  */

/* @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
?>

<div class="field comment-box">
    <label class="label" for="product-item-comment-<?= /* @escapeNotVerified */ $item->getWishlistItemId() ?>">
        <span><?= /* @escapeNotVerified */ __('Comment') ?></span>
    </label>
    <div class="control">
        <textarea id="product-item-comment-<?= /* @escapeNotVerified */ $item->getWishlistItemId() ?>" placeholder="<?= /* @escapeNotVerified */ $this->helper('Magento\Wishlist\Helper\Data')->defaultCommentString() ?>" name="description[<?= /* @escapeNotVerified */ $item->getWishlistItemId() ?>]" title="<?= /* @escapeNotVerified */ __('Comment') ?>" class="product-item-comment"><?= ($block->escapeHtml($item->getDescription())) ?></textarea>
    </div>
</div>
