<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<form action="" method="post" id="form-validate" class="form send confirmation" data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?= /* @escapeNotVerified */ __('* Required Fields') ?>">
        <p class="field note"><?= /* @escapeNotVerified */ __('Please enter your email below and we will send you the confirmation link.') ?></p>
        <div class="field email required">
            <label for="email_address" class="label"><span><?= /* @escapeNotVerified */ __('Email') ?></span></label>
            <div class="control">
                <input type="email" name="email" id="email_address" class="input-text" value="<?= $block->escapeHtml($block->getEmail()) ?>" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action send primary"><span><?= /* @escapeNotVerified */ __('Send confirmation link') ?></span></button>
        </div>
        <div class="secondary">
            <a href="<?= /* @escapeNotVerified */ $block->getLoginUrl() ?>" class="action back"><span><?= /* @escapeNotVerified */ __('Back to Sign In') ?></span></a>
        </div>
    </div>
</form>
