<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile

?>
<form class="form password forget"
      action="<?= /* @escapeNotVerified */ $block->getUrl('*/*/forgotpasswordpost') ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?= /* @escapeNotVerified */ __('* Required Fields') ?>">
        <div class="field note"><?= /* @escapeNotVerified */ __('Please enter your email address below to receive a password reset link.'); ?></div>
        <div class="field email required">
            <label for="email_address" class="label"><span><?= /* @escapeNotVerified */ __('Email') ?></span></label>
            <div class="control">
                <input type="email" name="email" alt="email" id="email_address" class="input-text" value="<?= $block->escapeHtml($block->getEmailValue()) ?>" data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <?= $block->getChildHtml('form_additional_info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary"><span><?= /* @escapeNotVerified */ __('Reset My Password') ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= /* @escapeNotVerified */ $block->getLoginUrl() ?>"><span><?= /* @escapeNotVerified */ __('Go back') ?></span></a>
        </div>
    </div>
</form>
