<div class="main-banner">
	<div class="banner no-margin">
	    <!-- <img src="<?php // echo $this->getUrl('pub/media')."wysiwyg/banner.jpg" ?>" alt="" /> -->
		<video autoplay loop muted>
			<source src="<?php echo $this->getUrl('pub/media')."wysiwyg/iStock-1351733015.mp4" ?>" type="video/mp4">
			<source src="<?php echo $this->getUrl('pub/media')."wysiwyg/iStock-1351733015.ogg" ?>" type="video/ogg">
		</video>
		<div class="part_search_form">
			<form id="vehicle_search_form">
				<div class="part_search_input_wrapper">
					<div class="part_search_input part_search_active">
						<input id="plate" type="radio" name="type" value="plate" class="part_search" checked>
						<!-- <label for="plate">Sök med Reg-nummer</label>  -->
						<label for="plate">Reg.nr sökning</label> 
					</div>
					<div class="part_search_input">
						<input id="oem" type="radio" name="type" value="oem" class="part_search">
						<!-- <label for="oem">Sök på OEM-nummer</label> -->
						<label for="oem">Sök på OEM-nummer</label>
					</div>
					<div class="part_search_input">
						<input id="vin" type="radio" name="type" value="vin" class="part_search">
						<!-- <label for="oem">Sök på OEM-nummer</label> -->
						<label for="vin">Sök på VIN-nummer</label>
					</div> 
					<div class="part_search_input">
						<input id="menual" type="radio" name="type" value="menual" class="part_search">
						<!-- <label for="menual">Manuel sökning</label>  -->
						<label for="menual">Manuel sökning</label> 
					</div>
				</div>
				<div class="part_search_submit">
					<input type="text" name="search_input" id="search_input" placeholder="Sök på regnr">
					<!-- <div class="part_search_submit-dropdown"> -->
						<select name="engine_type" id="engine_type">
							<option value=''>Välj alternativ</option>
						</select>
					
						<select name="engine_catalogue" id="engine_catalogue">
							<option value=''>Välj alternativ</option>
						</select>
					<!-- </div> -->
					
					<span class="search_reset_button" onclick="searchFormReset()"><i class="fa fa-times" aria-hidden="true"></i></span>
					<input id="search_part_button" type="submit" name="submit" value="Sök">
				</div>
				<span id="search_input_error" class="part_search-error">This is a required field</span>
				<span id="search_select_error" class="part_search-error">Both fields are required</span>
			</form>
		</div>
	</div>
</div>

<script type="text/javascript">
	require(['jquery', 'jquery/ui'], function($){ 
	    $(document).ready(function(){
	     	$('#vehicle_search_form').submit(function(evt){
	     		evt.preventDefault();
	     		var searchFor = $('#vehicle_search_form input[name="type"]:checked').val();
	     		$('#search_input_error, #search_select_error').hide();
	     		if(searchFor != 'menual' && $('#search_input').val() == ''){
	     			$('#search_input_error').show();
	     			return false;
	     		}
	     		if(searchFor == 'menual'){
	     			if($("#engine_type").val() == '' || $("#engine_catalogue").val() == ''){
		     			$('#search_select_error').show();
		     			return false;
	     			}
	     		}

     			if(searchFor == 'oem'){
     				var part_num = $('#search_input').val();
     				if (part_num.includes('#')) {
     					console.log(part_number,'#');
     					var part_number = part_num.replace("#", "`");
     				}else if (part_num.includes('FAE')) {
     					console.log(part_number,'FAE');
     					var part_number = part_num.replace("FAE", "");
     				}else if (part_num.includes('GEB')) {
     					console.log(part_number,'GEB');
     					var part_number = part_num.replace("GEB", "");
     				}else if (part_num.includes('CT')) {
     					console.log(part_number,'CT');
     					var part_number = part_num.replace("CT", "");
     				}else if (part_num.includes('COV/') && part_num.includes('/')) {
     					console.log(part_number,'COV');
     					var part_number = part_num.replace("COV/", "");
     					part_number = part_number.replace("/", "");
     				}else if (part_num.includes('D-')) {
     					console.log(part_number,'D-');
     					var part_number = part_num.replace("D-", "");
     				}else if (part_num.includes('EL')) {
     					console.log(part_number,'EL');
     					var part_number = part_num.replace("EL", "");
     				}else if (part_num.includes('DIN')) {
     					console.log(part_number,'DIN');
     					var part_number = part_num.replace("DIN", "");
     				}
     				else{
     					console.log(part_number,'else');
     					var part_number = $('#search_input').val();
     				}
     				window.location.href = '<?php  echo $this->getUrl('/'); ?>parts/index/index?partnumber='+part_number+'&&replacedoem=';
     			} else if(searchFor == 'vin'){
     				window.location.href = '<?php  echo $this->getUrl('/'); ?>parts/vehicle/index?vin='+$('#search_input').val();
     			} else if(searchFor == 'plate'){
     				window.location.href = '<?php  echo $this->getUrl('/'); ?>parts/vehicle/index?plate='+$('#search_input').val();
     			} else {
     				window.location.href = '<?php  echo $this->getUrl('/'); ?>parts/vehicle/index?menual='+$('#engine_catalogue').val();
     				
     			}
	     		
	     	});
			$(".part_search_input_wrapper :input").click(function () {
				$('#search_input_error, #search_select_error').hide();
			    $(".part_search_input_wrapper :input").each(function() {
			    	$("#search_input").val('');
			      	if ($(this).is(":checked")) {
				      	var placeholder_val = $(this).val();
				      	$("#search_input").attr("placeholder", "Sök på "+ placeholder_val +"-nummer");
				        $(this).parent().addClass('part_search_active');
			      	} else {
			        	$(this).parent().removeClass('part_search_active');
			      	}
			    });
			    if($('#vehicle_search_form input[name="type"]:checked').val() == 'menual'){
			    	$("#search_input").hide();
			    	$("#engine_type, #engine_catalogue").show();
			    } else {
			    	$("#search_input").show();
			    	$("#engine_type, #engine_catalogue").hide();
			    }
			});

			$.ajax({
			    url: "<?php echo $this->getUrl(); ?>pub/yqservice/engine_type.php?step=0&ssd=",
			    type: "GET",
			    success: function(data) {
			    	var html = '<option value="">Välj alternativ</option>';
			    	var options = JSON.parse(data);
			    	options = options[0].steps[0].options;
			    	options.forEach(function(e){
			    		html += '<option value="'+e.key+'">'+e.value+'</option>';
			    	});
			    	$('#engine_type').empty().append(html);
			    }
			});
	     	$('#engine_type').change(function(){
	     		if($(this).val() != ''){ 
		     		$.ajax({
					    url: "<?php echo $this->getUrl(); ?>pub/yqservice/engine_type.php?step=1&ssd="+$(this).val(),
					    type: "GET",
					    success: function(data) {
					    	var html = '<option value="">Välj alternativ</option>';
					    	var options = JSON.parse(data);
					    	options = options[0].steps[1].options;
					    	options.forEach(function(e){
					    		html += '<option value="'+e.key+'">'+e.value+'</option>';
					    	});
					    	$('#engine_catalogue').empty().append(html);
					    }
					});
	     		} else {
	     			var html = '<option value="">Välj alternativ</option>';
	     			$('#engine_catalogue').empty().append(html);
	     		}
	     	})
	    });
	});

	function searchFormReset() {
		document.getElementById("vehicle_search_form").reset();
	}
</script>
<style type="text/css">
	#search_input_error, #search_select_error{display: none; color: red;}
	#engine_type, #engine_catalogue{display: none;}
</style>