<?php
$isEnabledAjaxInfiniteScroll = $block->isEnabled();
$delay = !empty($block->dely()) ? $block->dely() : '100';
$content = !empty($block->content()) ? $block->content() : '.products.wrapper';
$pagination = !empty($block->pagination()) ? $block->pagination() : '.toolbar .pages';
$next = !empty($block->next()) ? $block->next() : '.page-item';
$item = !empty($block->item()) ? $block->item() : '.poster__item__wrapper';
$loadingImage = '';
if ($block->loadingImage() != '') {
    $loadingImage = $block->getMediaPath().'vision/ajax_infinite_scroll/'.$block->loadingImage();
}
$loadingText = !empty($block->loadingText()) ? $block->loadingText() : '';
$doneText = !empty($block->doneText()) ? $block->doneText() : '';
if ($isEnabledAjaxInfiniteScroll) {
    ?>
    <script>
        require(['jquery', 'Vision_AjaxInfiniteScroll/js/infinitescroll'], function ($) {
            $(document).ready(function () {
                var ias = $.vision({
                    container: "<?php echo $content;?>",
                    item: "<?php echo $item;?>",
                    pagination: "<?php echo $pagination;?>",
                    next: "<?php echo $next;?>",
                    delay: "<?php echo $delay;?>",
                });
                
                window.ias = $.vision();
                window.ias.extension(new VISIONSpinnerExtension({
                    src: "<?php echo $loadingImage; ?>", // override text when no pages left
                    html: '<div class="ias-spinner" style="text-align: center;font-size: 16px;color: #333;display: block;"><img style="display:inline" src="{src}"/><p><?php echo $loadingText; ?></p></div>'
                }));

                window.ias.on('noneLeft', jQuery.proxy(function(){
                    $lastItem = window.ias.getLastItem();
                    $lastItem.after("<div class='ias-noneleft' style='text-align: center;color: #333;letter-spacing: 0px;font-size: 14px;font-weight: 400;margin-top: 5rem;'><?php echo $doneText;?></div>");
                    jQuery('#load_more_prd').hide();
                }, this));
               

                window.ias.on('rendered', function(items){
                    $('body').trigger('contentUpdated');
                });
            });
        });
    </script>
    <?php
} ?>
