<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>

<div id="product_gallery">
    <?php foreach ($block->getGalleryImages() as $image): ?>
        <?php if ($image->getData('video_url')): ?>
            <div class="thumb video" style="padding-bottom: <?= /* @escapeNotVerified */ ($block->getImageAttribute('product_page_image_medium', 'height') / $block->getImageAttribute('product_page_image_medium', 'width') * 100) ?>%">
                <iframe width="100%" height="100%" src="<?= $image->getData('video_url') ?>" title="<?= $image->getData('video_title') ?>" frameborder="0" allowfullscreen></iframe>
            </div>
        <?php else: ?>
            <div class="thumb"><img src="<?= $image->getData('large_image_url'); ?>" alt=""></div>
        <?php endif;?>
    <?php endforeach; ?>
</div>
<div class="fotorama gallery-placeholder" data-gallery-role="gallery-placeholder"></div>

<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "stickyGallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= /* @escapeNotVerified */ $block->getMagnifier() ?>,
                "data": <?= /* @escapeNotVerified */ $block->getGalleryImagesJson() ?>,
                "desktopGallery": "#product_gallery",
                "leftColumn": "left_column",
                "rightColumn": "right_column",
                "rightColumnWrap": "right_column_wrap",
                "options": {
                    "nav": "dots",
                    "loop": <?= /* @escapeNotVerified */ $block->getVar("gallery/loop") ? 'true' : 'false' ?>,
                    "keyboard": false,
                    "arrows": false,
                    "allowfullscreen": false,
                    "showCaption": <?= /* @escapeNotVerified */ $block->getVar("gallery/caption") ? 'true' : 'false' ?>,
                    "width": "<?= /* @escapeNotVerified */ $block->getImageAttribute('product_page_image_medium', 'width'); ?>",
                    <?php if ($block->getImageAttribute('product_page_image_medium', 'height') || $block->getImageAttribute('product_page_image_medium', 'width')): ?>
                        "height": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_medium', 'height') ?: $block->getImageAttribute('product_page_image_medium', 'width'); ?>,
                    <?php endif; ?>
                    <?php if ($block->getVar("gallery/transition/duration")): ?>
                        "transitionduration": <?= /* @escapeNotVerified */ $block->getVar("gallery/transition/duration") ?>,
                    <?php endif; ?>
                    "transition": "<?= /* @escapeNotVerified */ $block->getVar("gallery/transition/effect") ?>",
                    "navarrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/navarrows") ? 'true' : 'false' ?>,
                    "navtype": "<?= /* @escapeNotVerified */ $block->getVar("gallery/navtype") ?>",
                    "navdir": "horizontal",
                    "controlsonstart" : 0,

                    "maxheight": "<?= /* @escapeNotVerified */ $block->getImageAttribute('product_page_image_medium', 'height') ?>"
                }
            }
        }
    }
</script>
