<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View*/
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');?>

<?php if($customerSession->isLoggedIn()) { ?>
    <div class="product-addto-links" data-role="add-to-links">
        <?= $block->getChildHtml() ?>
    </div>
<?php } ?>
